// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    public struct _7128f27b1ed1baf489c8389ed5d6fc89_6470917955799697127 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Single Speed;
            [FieldOffset(4)]
            public System.Byte Dead;
            [FieldOffset(5)]
            public System.Single Float_32_Value;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _7128f27b1ed1baf489c8389ed5d6fc89_6470917955799697127.SpeedMask;
            SpeedSimulationFrame = frame;
            FieldsMask |= _7128f27b1ed1baf489c8389ed5d6fc89_6470917955799697127.DeadMask;
            DeadSimulationFrame = frame;
            FieldsMask |= _7128f27b1ed1baf489c8389ed5d6fc89_6470917955799697127.Float_32_ValueMask;
            Float_32_ValueSimulationFrame = frame;
        }

        public static unsafe _7128f27b1ed1baf489c8389ed5d6fc89_6470917955799697127 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 9) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 9) " +
                    "for component with ID 20");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 20");
            }

            var orig = new _7128f27b1ed1baf489c8389ed5d6fc89_6470917955799697127();

            var comp = (Interop*)data;

            orig.Speed = comp->Speed;
            orig.Dead = comp->Dead != 0;
            orig.Float_32_Value = comp->Float_32_Value;

            return orig;
        }


        public static uint SpeedMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame SpeedSimulationFrame;
        public System.Single Speed;
        public static uint DeadMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame DeadSimulationFrame;
        public System.Boolean Dead;
        public static uint Float_32_ValueMask => 0b00000000000000000000000000000100;
        public AbsoluteSimulationFrame Float_32_ValueSimulationFrame;
        public System.Single Float_32_Value;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 20;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000111;
        public bool HasFields() => true;
        public bool HasRefFields() => false;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 3;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;


        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_7128f27b1ed1baf489c8389ed5d6fc89_6470917955799697127)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.SpeedSimulationFrame = other.SpeedSimulationFrame;
                this.Speed = other.Speed;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.DeadSimulationFrame = other.DeadSimulationFrame;
                this.Dead = other.Dead;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.Float_32_ValueSimulationFrame = other.Float_32_ValueSimulationFrame;
                this.Float_32_Value = other.Float_32_Value;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_7128f27b1ed1baf489c8389ed5d6fc89_6470917955799697127 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 3);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = data.Speed;



                bitStream.WriteFloat(fieldValue, FloatMeta.NoCompression());
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = data.Dead;



                bitStream.WriteBool(fieldValue);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = data.Float_32_Value;



                bitStream.WriteFloat(fieldValue, FloatMeta.NoCompression());
            }

            mask >>= 1;

            return mask;
        }

        public static _7128f27b1ed1baf489c8389ed5d6fc89_6470917955799697127 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(3);
            }

            var val = new _7128f27b1ed1baf489c8389ed5d6fc89_6470917955799697127();
            if (bitStream.ReadMask())
            {

                val.Speed = bitStream.ReadFloat(FloatMeta.NoCompression());
                val.FieldsMask |= _7128f27b1ed1baf489c8389ed5d6fc89_6470917955799697127.SpeedMask;
            }
            if (bitStream.ReadMask())
            {

                val.Dead = bitStream.ReadBool();
                val.FieldsMask |= _7128f27b1ed1baf489c8389ed5d6fc89_6470917955799697127.DeadMask;
            }
            if (bitStream.ReadMask())
            {

                val.Float_32_Value = bitStream.ReadFloat(FloatMeta.NoCompression());
                val.FieldsMask |= _7128f27b1ed1baf489c8389ed5d6fc89_6470917955799697127.Float_32_ValueMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_7128f27b1ed1baf489c8389ed5d6fc89_6470917955799697127(" +
                $" Speed: { this.Speed }" +
                $" Dead: { this.Dead }" +
                $" Float_32_Value: { this.Float_32_Value }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(3, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(3, '0') })";
        }
    }

}
