// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_cc21e0b721af6554cb6d76410a471081_38c641830bba43b198468f030824f427 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_cc21e0b721af6554cb6d76410a471081_6dca2d79fa2746b9b3ee56317ac176c0 : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_cc21e0b721af6554cb6d76410a471081_1249811188870620346);
        public override string CoherenceComponentName => "_cc21e0b721af6554cb6d76410a471081_1249811188870620346";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Forward_32_Input;

            var simFrame = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Forward_32_InputSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Forward_32_Input = Value;
            }
            else
            {
                update.Forward_32_Input = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.Forward_32_InputSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _cc21e0b721af6554cb6d76410a471081_1249811188870620346();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_cc21e0b721af6554cb6d76410a471081_7d12dd4a2cdd4ff2ae7342b2841ae5e7 : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_cc21e0b721af6554cb6d76410a471081_1249811188870620346);
        public override string CoherenceComponentName => "_cc21e0b721af6554cb6d76410a471081_1249811188870620346";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Horizontal_32_Input;

            var simFrame = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Horizontal_32_InputSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Horizontal_32_Input = Value;
            }
            else
            {
                update.Horizontal_32_Input = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.Horizontal_32_InputSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _cc21e0b721af6554cb6d76410a471081_1249811188870620346();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_cc21e0b721af6554cb6d76410a471081_7b382ee74e1f49aebe223c5b21e88f55 : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_cc21e0b721af6554cb6d76410a471081_1249811188870620346);
        public override string CoherenceComponentName => "_cc21e0b721af6554cb6d76410a471081_1249811188870620346";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Yaw_32_Input;

            var simFrame = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Yaw_32_InputSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Yaw_32_Input = Value;
            }
            else
            {
                update.Yaw_32_Input = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.Yaw_32_InputSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _cc21e0b721af6554cb6d76410a471081_1249811188870620346();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_cc21e0b721af6554cb6d76410a471081_1b4c230a1b794e6cb808e64abd15a16a : IntAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_cc21e0b721af6554cb6d76410a471081_1249811188870620346);
        public override string CoherenceComponentName => "_cc21e0b721af6554cb6d76410a471081_1249811188870620346";
        public override uint FieldMask => 0b00000000000000000000000000001000;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.GetInteger(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetInteger(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Int_32_Value;

            var simFrame = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Int_32_ValueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Int_32_Value = Value;
            }
            else
            {
                update.Int_32_Value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.Int_32_ValueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _cc21e0b721af6554cb6d76410a471081_1249811188870620346();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_cc21e0b721af6554cb6d76410a471081_7169827e6ec648c29db6341ae05fbce0 : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_cc21e0b721af6554cb6d76410a471081_1249811188870620346);
        public override string CoherenceComponentName => "_cc21e0b721af6554cb6d76410a471081_1249811188870620346";
        public override uint FieldMask => 0b00000000000000000000000000010000;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Float_32_Value;

            var simFrame = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Float_32_ValueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Float_32_Value = Value;
            }
            else
            {
                update.Float_32_Value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.Float_32_ValueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _cc21e0b721af6554cb6d76410a471081_1249811188870620346();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_cc21e0b721af6554cb6d76410a471081_1a1135c51f0443d98deacfb93cd512bf : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_cc21e0b721af6554cb6d76410a471081_1249811188870620346);
        public override string CoherenceComponentName => "_cc21e0b721af6554cb6d76410a471081_1249811188870620346";
        public override uint FieldMask => 0b00000000000000000000000000100000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Bool_32_Value;

            var simFrame = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Bool_32_ValueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Bool_32_Value = Value;
            }
            else
            {
                update.Bool_32_Value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.Bool_32_ValueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _cc21e0b721af6554cb6d76410a471081_1249811188870620346();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_cc21e0b721af6554cb6d76410a471081_c74a501cb40745ee84b6903808e32d33 : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_cc21e0b721af6554cb6d76410a471081_1249811188870620346);
        public override string CoherenceComponentName => "_cc21e0b721af6554cb6d76410a471081_1249811188870620346";
        public override uint FieldMask => 0b00000000000000000000000001000000;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Force;

            var simFrame = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).ForceSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Force = Value;
            }
            else
            {
                update.Force = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.ForceSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _cc21e0b721af6554cb6d76410a471081_1249811188870620346();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_cc21e0b721af6554cb6d76410a471081_84950df3392a4734987380981c61cf84 : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_cc21e0b721af6554cb6d76410a471081_1249811188870620346);
        public override string CoherenceComponentName => "_cc21e0b721af6554cb6d76410a471081_1249811188870620346";
        public override uint FieldMask => 0b00000000000000000000000010000000;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Leg;

            var simFrame = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).LegSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Leg = Value;
            }
            else
            {
                update.Leg = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.LegSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _cc21e0b721af6554cb6d76410a471081_1249811188870620346();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_cc21e0b721af6554cb6d76410a471081_f832a7d2e9d9428e84625bb8b0391dd3 : IntAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_cc21e0b721af6554cb6d76410a471081_1249811188870620346);
        public override string CoherenceComponentName => "_cc21e0b721af6554cb6d76410a471081_1249811188870620346";
        public override uint FieldMask => 0b00000000000000000000000100000000;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.GetInteger(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetInteger(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Item_32_ID;

            var simFrame = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Item_32_IDSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Item_32_ID = Value;
            }
            else
            {
                update.Item_32_ID = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.Item_32_IDSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _cc21e0b721af6554cb6d76410a471081_1249811188870620346();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_cc21e0b721af6554cb6d76410a471081_9156a51f1a61416dbe3fd4b67d3d82e0 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_cc21e0b721af6554cb6d76410a471081_1249811188870620346);
        public override string CoherenceComponentName => "_cc21e0b721af6554cb6d76410a471081_1249811188870620346";
        public override uint FieldMask => 0b00000000000000000000001000000000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Moving;

            var simFrame = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).MovingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Moving = Value;
            }
            else
            {
                update.Moving = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.MovingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _cc21e0b721af6554cb6d76410a471081_1249811188870620346();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_cc21e0b721af6554cb6d76410a471081_1cb6c95d85e4482997bbbe23bb248f20 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_cc21e0b721af6554cb6d76410a471081_1249811188870620346);
        public override string CoherenceComponentName => "_cc21e0b721af6554cb6d76410a471081_1249811188870620346";
        public override uint FieldMask => 0b00000000000000000000010000000000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Item_32_Use;

            var simFrame = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Item_32_UseSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Item_32_Use = Value;
            }
            else
            {
                update.Item_32_Use = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.Item_32_UseSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _cc21e0b721af6554cb6d76410a471081_1249811188870620346();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_cc21e0b721af6554cb6d76410a471081_8a03c3c6f32947a4abd3c1189ab45a76 : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_cc21e0b721af6554cb6d76410a471081_1249811188870620346);
        public override string CoherenceComponentName => "_cc21e0b721af6554cb6d76410a471081_1249811188870620346";
        public override uint FieldMask => 0b00000000000000000000100000000000;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Speed_32_Multiplier;

            var simFrame = ((_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent).Speed_32_MultiplierSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_cc21e0b721af6554cb6d76410a471081_1249811188870620346)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Speed_32_Multiplier = Value;
            }
            else
            {
                update.Speed_32_Multiplier = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.Speed_32_MultiplierSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _cc21e0b721af6554cb6d76410a471081_1249811188870620346();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_cc21e0b721af6554cb6d76410a471081 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_cc21e0b721af6554cb6d76410a471081>();
        
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["38c641830bba43b198468f030824f427"] = new Binding_cc21e0b721af6554cb6d76410a471081_38c641830bba43b198468f030824f427(),
			["6dca2d79fa2746b9b3ee56317ac176c0"] = new Binding_cc21e0b721af6554cb6d76410a471081_6dca2d79fa2746b9b3ee56317ac176c0(),
			["7d12dd4a2cdd4ff2ae7342b2841ae5e7"] = new Binding_cc21e0b721af6554cb6d76410a471081_7d12dd4a2cdd4ff2ae7342b2841ae5e7(),
			["7b382ee74e1f49aebe223c5b21e88f55"] = new Binding_cc21e0b721af6554cb6d76410a471081_7b382ee74e1f49aebe223c5b21e88f55(),
			["1b4c230a1b794e6cb808e64abd15a16a"] = new Binding_cc21e0b721af6554cb6d76410a471081_1b4c230a1b794e6cb808e64abd15a16a(),
			["7169827e6ec648c29db6341ae05fbce0"] = new Binding_cc21e0b721af6554cb6d76410a471081_7169827e6ec648c29db6341ae05fbce0(),
			["1a1135c51f0443d98deacfb93cd512bf"] = new Binding_cc21e0b721af6554cb6d76410a471081_1a1135c51f0443d98deacfb93cd512bf(),
			["c74a501cb40745ee84b6903808e32d33"] = new Binding_cc21e0b721af6554cb6d76410a471081_c74a501cb40745ee84b6903808e32d33(),
			["84950df3392a4734987380981c61cf84"] = new Binding_cc21e0b721af6554cb6d76410a471081_84950df3392a4734987380981c61cf84(),
			["f832a7d2e9d9428e84625bb8b0391dd3"] = new Binding_cc21e0b721af6554cb6d76410a471081_f832a7d2e9d9428e84625bb8b0391dd3(),
			["9156a51f1a61416dbe3fd4b67d3d82e0"] = new Binding_cc21e0b721af6554cb6d76410a471081_9156a51f1a61416dbe3fd4b67d3d82e0(),
			["1cb6c95d85e4482997bbbe23bb248f20"] = new Binding_cc21e0b721af6554cb6d76410a471081_1cb6c95d85e4482997bbbe23bb248f20(),
			["8a03c3c6f32947a4abd3c1189ab45a76"] = new Binding_cc21e0b721af6554cb6d76410a471081_8a03c3c6f32947a4abd3c1189ab45a76(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_cc21e0b721af6554cb6d76410a471081()
        {
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_cc21e0b721af6554cb6d76410a471081 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_cc21e0b721af6554cb6d76410a471081>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
